[package]
name = "vtt-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[[bin]]
name = "vtt-cli"
path = "src/main.rs"

[dependencies]
vtt-core = { path = "../vtt-core" }
anyhow.workspace = true
clap.workspace = true
